name: Maven Package and Google Cloud Deploy

on:
  push:
    branches:
      - backend-cicd  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Add Environment Variables
      run: |
          echo "GOOGLE_MAPS_KEY=AIzaSyCJ0SiMfKRo3a2Vzfo-x6aBAN_Sbd847WY" > .env.properties
          echo "CARBON_INTERFACE_KEY=SgFJ1VjkTCAWZDUGl65Rg" >> .env.properties
      working-directory: ./sustainable_commute_finder/
      
    - name: Maven Package
      run: mvn clean package
      working-directory: ./sustainable_commute_finder/

    - name: Deploy to Google Cloud App Engine
      run: gcloud app deploy sustainable_commute_finder/target/sustainable_commute_finder-0.0.1-SNAPSHOT.jar
      working-directory: ./sustainable_commute_finder/
