name: Maven Package and Google Cloud Deploy

on:
  push:
    branches:
      - backend-cicd  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Add Environment Variables
      run: |
          echo "GOOGLE_MAPS_KEY=AIzaSyCJ0SiMfKRo3a2Vzfo-x6aBAN_Sbd847WY" > .env.properties
          echo "CARBON_INTERFACE_KEY=SgFJ1VjkTCAWZDUGl65Rg" >> .env.properties
      working-directory: ./sustainable_commute_finder/
      
    - name: Maven Package
      run: mvn clean package
      working-directory: ./sustainable_commute_finder/

    - name: Setup Google Cloud SDK
      # You may pin to the exact commit or the version.
      # uses: mathieu-bour/setup-gcloud@3bb09468aad23fb31bd9e873e87a189d845063c3
      uses: mathieu-bour/setup-gcloud@1.3.1
      with:
        # The service account key to use, base64-encoded.
        service-account-key: "98839b643aad3236de312a54adf6de2758050f38"
        # The default Google Cloud project. You can change it later.
        project: "ecotransit-401621"
