name: Google Cloud Deploy

on:
  push:
    branches: 
      - main
    paths:
      - sustainable_commute_finder/**

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
        
    - name: 'Deploy Application'
      run: |
           gcloud app deploy
      working-directory: ./sustainable_commute_finder/
     

      
