name: Deploy to GCP

on:
  push: 
    branches:
      - main
    paths:
      - frontend/**
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: frontend/deploy

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_FRONTEND }}'
        
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Deploy
        run: |
          gcloud app deploy deploy/
        
      
