name: Deploy to GCP

on:
  workflow_run:
    workflows: 
      - Build React Project
    branches: 
      - frontend-deploy
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      
      - name: Test
        run: |
              ls && ls/build-artifacts

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_FRONTEND }}'
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
         version: '>= 363.0.0'
        
      
